url: "http://jakewharton.com"

highlighter: rouge
permalink: /:title/
markdown: kramdown

future: true

gems:
  - jekyll-feed

collections:
  presentations:
    output: true
    permalink: /presentation/:path/

exclude: [vendor]
