url: "http://jakewharton.com"

highlighter: pygments
permalink: /:title/
markdown: redcarpet

gems:
  - jekyll-feed

collections:
  presentations:
    output: true
    permalink: /presentation/:path/
